language: node_js
node_js: '13'
script:
- yarn build
cache: yarn
deploy:
  provider: npm
  edge: true
  email: domoritz@gmail.com
  on:
    tags: true
    repo: vega/vega-datasets
  api_key:
    secure: uuzQbyjuRV8fgLjWFkOPRl/pPvMc/PiwMcuDKOkNlTqATgcpWC7lsjpMOMnZe4DG4hlPDj0WsOT9ZDF0/lN4mpVw9mTQpFnU9u5Y+HFH4HzckChmNO176unBR2rBfnhwLR/ogR/IyZKMovbTxNPdP7k2uJmyc6jCOwMybv86ytNq1U2oo1XsOGod6mYCnXRtCu7zpRfFTJxQIVa5Jk41Gf+EZKDBblv4K8WgULkBKPfoy6CqY8YcdDUCM26NvX0YZSf4lfxbJEXww4I2+mOZ1iUiamOHKq3dwXws1b+xoEAkAwI4yccDXCKBA0Zb9FlQ+cUb6G1UqgORU7hdnaLqFKOjyGubQZm6UUJZ0QCA3z0jQBWibxBW4y+H+reL/UnI/jr7Q7+FZNpO9ASDxLuZbc2wdN11hIkadGVf3QmiwgahwlmS8gwi8tdBu9oliSRXL80xQQg+wjq8lM/Pb/ECdKN5xCvpDAFuzuT4CRLPZ1VCdKjkqr+OISlz9RcMGPKFIFAZRdVbXHVkmafxLykOpIiXbKjJPr6fT1MWnie48ibE5bMz2MTagJQawj375wD1ZE24CexlwDpUQTg33fF3cQAlR3FAh+I0RSyKZLvk3SG3zkxvkQF5C4Zs6gxupoEVwWxWZt5QWxf1obI7nlGsQhq/62STDBxJVouDlk2qXBs=
